### ISSUE TITLE
Deprecated Methods  (addNewsfeedChangedHandler)

### ISSUE THREAD

**Issue by cliffgr** [Leanplum/Leanplum-Android-SDK-Example#2]
Please update you Example project with newer version of Inbox 

`  Leanplum.newsfeed().addNewsfeedChangedHandler(new NewsfeedChangedCallback() {

            @Override
            public void newsfeedChanged() {

            }
        });`

**Comment by benmarten** [comment]
@milos1290 If you have time in your sprint, could you please take a look at this? Thanks

**Comment by benmarten** [comment]
I'v pushed this branch: https://github.com/Leanplum/Leanplum-Android-SDK-Example/tree/feature/refactor-newsfeed

There's still a build an issue here: https://github.com/Leanplum/Leanplum-Android-SDK-Example/blob/feature/refactor-newsfeed/app/src/main/java/com/leanplum/android/example/fragments/AppInboxFragment.java#L76

Not sure how to use of: https://github.com/Leanplum/Leanplum-Android-SDK/blob/develop/AndroidSDK/src/com/leanplum/LeanplumInbox.java#L359

@Enuviel can you please help?

**Comment by cliffgr** [comment]
@benmarten  use this method:

>     Have to stay as is because of backward compatibility + generics super-sub incompatibility
>     (http://www.angelikalanger.com/GenericsFAQ/FAQSections/ParameterizedTypes.html#Topic2).
>     <p>
>     Returns a List containing all of the newsfeed messages sorted chronologically ascending (i.e.
>     the oldest first and the newest last).
>    
>   public List<NewsfeedMessage> allMessages() {
>     return allMessages(new ArrayList<NewsfeedMessage>());
>   }

here is my code :+1: 


```
final LeanplumInbox inbox = Leanplum.getInbox();
        inbox.addChangedHandler(new InboxChangedCallback() {
            @Override
            public void inboxChanged() {
                List all = inbox.allMessages();
                List<LeanplumInboxMessage> messages = (List<LeanplumInboxMessage>) all;
                Collections.reverse(messages);
                adapter.addMessages(messages);
            }
        });
```

**Comment by Enuviel** [comment]
@cliffgr  yes, you are right. Thank you!
@benmarten opened PR from your branch, looks like we can close this issue.

**Comment by benmarten** [comment]
resolved by https://github.com/Leanplum/Leanplum-Android-SDK-Example/pull/3
